// Shared copy + content data for both variations of the Projete-se landing.
window.CONTENT = {
  brand: 'Projete-se',
  price: 'R$97',
  bar: {
    line: 'Projete-se — R$97 · Acesso imediato · Garantia de 14 dias',
    cta: 'Quero começar agora',
  },
  hero: {
    tag: 'Para arquitetas em início de trajetória ou em fase de reorganização profissional',
    titleA: 'Você não está perdida.',
    titleB: 'Só está sem direção.',
    body: 'E nenhum curso técnico, nenhuma aula de SketchUp e nenhum vídeo no YouTube vai resolver isso, porque nenhum deles foi criado para te ajudar a entender seu momento antes de agir.',
    cta: 'Quero clareza sobre meu momento agora',
    sub: 'R$97 · Acesso imediato · Garantia de 14 dias',
    pills: [
      { icon: 'shield', label: 'Garantia de 14 dias' },
      { icon: 'bolt', label: 'Acesso imediato' },
      { icon: 'phone', label: 'Acesse de qualquer dispositivo' },
      { icon: 'mic', label: 'Bônus - Turma Fundadora' },
      { icon: 'clipboard', label: 'Bônus - Guia de Processos' },
    ],
  },
  pains: {
    tag: 'O que você está vivendo agora',
    title: 'Talvez o problema não seja falta de esforço.',
    lead: 'Você se dedica. Você estuda. Você tenta. Mas tem algo que continua faltando — e você sente isso toda vez que para um segundo para pensar no que está construindo.',
    items: [
      { n: '01', text: 'Você está sempre ocupada, mas ao fim do dia não sabe exatamente o que de fato está construindo com tanto esforço.' },
      { n: '02', text: 'Sua rotina funciona mais no improviso e na correria do que em uma direção clara. Você resolve tudo — mas sente que está sempre atrasada.' },
      { n: '03', text: 'Você olha para outras arquitetas e não entende por que elas parecem saber exatamente para onde estão indo — e você não.' },
      { n: '04', text: 'O próximo passo não está claro. Você não sabe se quer escritório próprio, se quer trabalhar para alguém, como cobrar o que vale, o que comunicar. Tudo ainda parece muito solto.' },
      { n: '05', text: 'Você sente que tem potencial — mas ainda não sabe como colocá-lo a funcionar de forma organizada e com intenção.' },
    ],
    pull: 'E isso não é falta de capacidade. É falta de leitura do momento.',
  },
  falseSolutions: {
    tag: 'Por que nada funcionou até agora',
    title: 'Você já tentou. Mas as soluções erradas não resolvem o problema certo.',
    lead: 'O mercado está cheio de conteúdo para arquitetas. Cursos, vídeos, mentorias, templates. Você já consumiu boa parte disso. E no fundo sabe que o problema não é falta de informação.',
    items: [
      { icon: 'play', title: 'YouTube e redes sociais', body: 'Muito conteúdo, nenhuma direção. Você aprende, consome, salva. E continua no mesmo lugar porque ninguém te perguntou primeiro onde você está.' },
      { icon: 'monitor', title: 'Cursos técnicos (SketchUp, Revit...)', body: 'Você aprendeu o software. Mas dominar a ferramenta não diz para você como, para quem e por que usá-la. A clareza não está na técnica.' },
      { icon: 'clipboard', title: 'Cursos de gestão e negócios', body: '"Aprenda a montar seu escritório em 10 passos." Ótimo — mas e quando você nem sabe que tipo de profissional quer ser? Construir sobre confusão é diferente de construir sobre clareza.' },
      { icon: 'bolt', title: 'Trabalhar mais e mais forte', body: 'Esforço sem direção só cansa mais rápido. Você não precisa de mais ação agora — precisa de mais clareza sobre para onde a ação deve ir.' },
    ],
    callout: {
      title: 'O que ninguém diz',
      body: 'Todos esses produtos assumem que você já sabe quem é como profissional. Mas e se você ainda estiver descobrindo isso?\nNenhum deles foi criado para a fase anterior — a fase em que você ainda está tentando entender seu momento, identificar suas dores reais e definir sua direção antes de agir.\nEsse espaço estava vazio. Até agora.',
    },
  },
  product: {
    tag: 'Apresentando',
    title: 'Projete-se',
    subtitle: 'Um processo de clareza e estrutura para arquitetas',
    nots: [
      'Não é um curso técnico',
      'Não é autoajuda',
      'Não é motivação vazia',
      'Não é fórmula pronta',
    ],
    body: 'É um material digital guiado — uma experiência de leitura, percepção e aplicação criada para te ajudar a entender onde você está, organizar o que você sente e construir seus próximos passos com mais clareza e intenção.',
    cta: 'Quero começar com clareza',
    sub: 'R$97 · Acesso imediato',
  },
  profiles: {
    tag: 'Para quem é o Projete-se',
    title: 'Nem toda arquiteta vive a profissão do mesmo jeito.',
    lead: 'O Projete-se foi criado para diferentes fases da carreira — porque cada momento pede uma leitura diferente. Encontre onde você está agora:',
    items: [
      { letter: 'A', name: 'Exploradora', quote: 'Estou tentando entender meu lugar.', body: 'Você está começando ou prestes a entrar no mercado — mas ainda sem clareza de como construir sua atuação com direção, segurança e identidade.' },
      { letter: 'B', name: 'Realizadora', quote: 'Eu faço muita coisa, mas tudo parece bagunçado.', body: 'Você já atende, já entrega. Mas muita coisa ainda depende do improviso, da correria e da sua energia para tudo funcionar.' },
      { letter: 'C', name: 'Expansora', quote: 'Quero crescer, mas desse jeito está pesado demais.', body: 'Você não está mais no início. Existe movimento e experiência — mas o peso da rotina torna o crescimento mais difícil do que deveria.' },
      { letter: 'D', name: 'Experiente', quote: 'Já caminhei bastante, mas sinto que preciso me reencontrar.', body: 'Você acumulou bagagem e prática. Mas algo estagnou, e você precisa de uma nova leitura sobre direção e próximos passos.' },
    ],
    quote: 'Não existe resposta certa. Existe identificação. O Projete-se começa exatamente de onde você está.',
  },
  process: {
    tag: 'O que você recebe',
    title: 'Um processo em etapas. Cada uma com propósito.',
    lead: 'Você não lê e pronto. Você percorre um processo — da orientação inicial até a aplicação prática, com apoio da IA para ir mais fundo em cada percepção.',
    items: [
      { n: '00', title: 'Orientação de Uso', body: 'Antes de começar, você entende como percorrer o material, qual é a lógica do processo e como a IA vai te ajudar ao longo de cada etapa. Nada de pular direto — o começo certo muda tudo.' },
      { n: '01', title: 'Mapa de Clareza', body: 'Você responde 8 perguntas honestas sobre sua vida profissional hoje. O resultado revela seu perfil atual — Exploradora, Realizadora, Expansora ou Experiente — e indica por onde sua leitura deve começar, com a rota personalizada para o seu momento.' },
      { n: '02', title: 'Guia de Percepções', body: 'O material principal — 69 páginas de reflexões estratégicas organizadas por perfil, sobre profissão, atuação e trajetória. Leve na forma. Profundo no conteúdo. Você não precisa ler tudo de uma vez — começa pelo que hoje mais pede clareza.' },
      { n: '03', title: 'IA + Aplicação', body: 'Aqui a leitura vira movimento. Com orientações práticas e a IA como ferramenta de apoio, você transforma percepções em direcionamentos concretos — organiza pensamentos, amplia clareza e define os próximos passos com mais intenção.' },
      { n: '+', title: 'Vídeos Guia com Letícia', body: 'Em cada etapa, Letícia aparece em vídeo para te orientar — explicando como aproveitar o material ao máximo, o que observar e como avançar com mais segurança. É como ter a mentora do seu lado enquanto você percorre o processo.' },
      { n: '↗', title: 'Suporte', body: 'Você não fica sem amparo. O suporte permanece disponível ao longo de todo o seu acesso para dúvidas e sustentação da experiência.' },
    ],
  },
  transformation: {
    tag: 'O antes e o depois',
    title: 'O que muda depois do Projete-se',
    before: {
      label: 'Antes — O que você vive hoje',
      items: [
        'Dúvida sobre como e por onde começar a construir a carreira',
        'Visão solta e confusa do que quer ser como profissional',
        'Sensação de pouca direção e propósito no dia a dia',
        'Percepção confusa do próprio momento profissional',
        'Muito esforço, pouca clareza do que está construindo',
      ],
    },
    after: {
      label: 'Depois — O que o Projete-se entrega',
      items: [
        'Mais entendimento sobre sua fase profissional e o que ela pede',
        'Mais clareza sobre profissão, direção e identidade',
        'Mais estrutura de pensamento para tomar decisões com intenção',
        'Mais consciência sobre os próximos passos que fazem sentido para você',
        'Construção profissional mais intencional, menos reativa',
      ],
    },
  },
  mentor: {
    tag: 'Quem criou o Projete-se',
    name: 'Letícia Schneider',
    role: 'Arquiteta · Criadora do Projete-se',
    location: 'Vale do Araguaia · Escritório próprio · Método replicável',
    lead: 'Arquiteta. Que um dia também estava sem direção — e não encontrou nenhum material que a ajudasse a entender seu momento antes de agir.',
    body: [
      'Letícia Schneider sabe exatamente o que você está vivendo — porque ela viveu também.',
      'Quando começou como arquiteta, tinha vontade, tinha habilidade, mas não tinha clareza. Não sabia bem para onde ir, o que priorizar, que tipo de profissional queria construir. Ela procurou um material que a ajudasse a entender seu próprio momento — e não encontrou nada.',
      'Só cursos técnicos. Só gestão de escritório. Só conteúdo para quem já sabia quem era e só precisava de mais ferramentas.',
      'Ela construiu o próprio caminho. Criou seu escritório no Vale do Araguaia, desenvolveu uma metodologia que funcionou para ela — e que pode funcionar para você.',
      'O Projete-se nasceu da lacuna que ela viveu na pele. Para que nenhuma outra arquiteta precise começar sem o ponto de partida certo.',
    ],
    quote: 'Nem sempre o que você precisa é de mais informação. Às vezes, é só do ponto de partida certo.',
    quoteBy: 'Letícia Schneider',
  },
  bonus: {
    tag: 'E tem mais',
    title: 'Além do material, você ainda ganha estes bônus:',
    label: 'BÔNUS - TURMA FUNDADORA — incluso na oferta',
    name: 'Mentoria em vídeo em grupo com Letícia Schneider — 40 minutos',
    body: 'Uma mentoria em vídeo em grupo exclusiva para quem entra na Turma Fundadora do Projete-se. São 40 minutos com Letícia para aprofundar percepções do material e receber orientação direta sobre o seu momento profissional.',
    body2: 'Você não fica sozinha no processo. Ter acesso à mentora que criou o material é o diferencial que transforma um produto digital em uma experiência real de acompanhamento.',
    note: 'Nenhum dos outros produtos do mercado oferece isso por R$97.',
    value: 'Valor real: R$197 — incluso na sua compra',
    items: [
      {
        label: 'BÔNUS - TURMA FUNDADORA — incluso na oferta',
        badge: 'Bônus - Turma Fundadora',
        name: 'Mentoria em vídeo em grupo com Letícia Schneider — 40 minutos',
        body: 'Uma mentoria em vídeo em grupo exclusiva para quem entra na Turma Fundadora do Projete-se. São 40 minutos com Letícia para aprofundar percepções do material e receber orientação direta sobre o seu momento profissional.',
        body2: 'Você não fica sozinha no processo. Ter acesso à mentora que criou o material é o diferencial que transforma um produto digital em uma experiência real de acompanhamento.',
        note: 'Nenhum dos outros produtos do mercado oferece isso por R$97.',
        value: 'R$197',
      },
      {
        label: 'BÔNUS - GUIA DE PROCESSOS — incluso na oferta',
        badge: 'Bônus - Guia de Processos',
        name: 'Guia de Processos',
        body: 'Um passo a passo claro com todas as fases de projeto, do atendimento inicial à entrega final, organizado em etapas práticas e aplicáveis ao dia a dia de profissionais de arquitetura ou engenharia.',
        bullets: [
          'Reduz o improviso e aumenta a previsibilidade.',
          'Evita retrabalhos e desgastes com o cliente.',
          'Fortalece sua imagem como profissional organizada, cuidadosa e comprometida com a excelência.',
        ],
        note: 'Para você transformar clareza em processo, rotina e entrega profissional.',
        value: 'R$97',
        guide: true,
      },
    ],
  },
  pricing: {
    tag: 'Tudo o que você está levando',
    title: 'A oferta completa',
    items: [
      { name: 'Projete-se — Material Digital Guiado (69 páginas)', value: 'R$197' },
      { name: 'Mapa de Clareza + 4 perfis personalizados', value: 'R$97' },
      { name: 'Vídeos guia com Letícia em cada etapa', value: 'R$97' },
      { name: 'Etapa IA + Aplicação — prompts e direcionamentos', value: 'R$67' },
      { name: 'Suporte e acesso permanente', value: 'R$47' },
      { name: 'BÔNUS — Turma Fundadora: mentoria em vídeo em grupo com Letícia (40min)', value: 'R$197', bonus: true },
      { name: 'BÔNUS — Guia de Processos: fases de projeto do atendimento inicial à entrega final', value: 'R$97', bonus: true },
    ],
    total: 'R$799',
    today: 'R$97',
    installment: '12x de R$11,54',
    installmentPrefix: '12x de',
    installmentValue: 'R$11,54',
    cashLine: 'ou R$97 à vista',
    todayLine: 'Você paga hoje:',
    framing: 'Menos do que um jantar. Menos do que uma consulta. Mais do que clareza sobre toda a sua carreira.',
    cta: 'Sim, quero o Projete-se agora',
    sub: 'Clique, pague e receba o acesso em segundos. Kiwify · Pagamento seguro',
    compare: [
      'Cursos técnicos como SketchUp e Revit custam de R$97 a R$299 — e não te dizem para onde ir com a ferramenta.',
      'Programas de gestão de escritório custam até R$497 — e assumem que você já sabe quem é.',
      'O Projete-se custa R$97. E começa exatamente de onde você está.',
    ],
  },
  guarantee: {
    title: 'Garantia de 14 dias',
    body: 'Se em 14 dias você sentir que o Projete-se não é para você, é só me enviar um e-mail e eu devolvo 100% do valor — sem perguntas, sem burocracia.',
    note: 'Compra sem risco. Totalmente.',
    cta: 'Quero começar com clareza',
  },
  faq: {
    tag: 'Perguntas frequentes',
    title: 'Suas dúvidas, respondidas.',
    items: [
      { q: 'Isso é para mim se eu ainda estou na faculdade?', a: 'Sim. Se você está no último ano ou prestes a entrar no mercado e já sente aquela sensação de "e agora?" — o Projete-se foi criado exatamente para esse momento. Quanto antes você tiver clareza sobre quem é como profissional, mais segura e intencional vai ser sua entrada no mercado.' },
      { q: 'Funciona para quem já atua há alguns anos?', a: 'Sim. O Projete-se tem etapas específicas para quem está em fase de reorganização profissional — os perfis Realizadora, Expansora e Experiente foram criados para arquitetas que já atuam mas sentem que algo está solto, pesado ou travado. O material começa de onde você está hoje, não de onde você começou.' },
      { q: 'Preciso usar a IA obrigatoriamente?', a: 'Não. A IA é um recurso de apoio dentro do processo — não é o produto. Você percorre as etapas de leitura e percepção normalmente, e a IA entra como uma ferramenta complementar para quem quiser aprofundar ainda mais as respostas. Funciona perfeitamente sem ela.' },
      { q: 'Quanto tempo tenho para acessar o material?', a: 'O acesso é permanente. Você pode percorrer no seu ritmo, voltar quantas vezes quiser, relembrar etapas específicas conforme sua carreira evolui. O Projete-se não é um conteúdo que você consome uma vez — é um processo ao qual você pode sempre retornar.' },
      { q: 'Quando acontece a mentoria ao vivo com Letícia?', a: 'As datas das sessões de mentoria em grupo são divulgadas dentro da plataforma. Ao comprar, você garante a sua vaga na próxima turma. Caso não consiga participar ao vivo, a gravação fica disponível para quem adquirir o acesso à gravação por R$47,90.' },
      { q: 'Qual é a forma de pagamento?', a: 'Pagamento único de R$97 via cartão de crédito, débito ou Pix, ou 12x de R$11,54. O acesso é liberado imediatamente após a confirmação do pagamento, direto pela plataforma Kiwify.' },
      { q: 'E se eu não gostar?', a: 'Garantia de 14 dias, sem perguntas. Se por qualquer motivo o Projete-se não fizer sentido para você, é só enviar um e-mail dentro do prazo e devolvo 100% do valor. Compra totalmente sem risco.' },
    ],
  },
  close: {
    title: 'Você tem dois caminhos a partir daqui.',
    pathA: 'Continuar como está — ocupada, esforçada, e ainda sem saber exatamente o que está construindo com tanto empenho.',
    pathB: 'Ou começar o processo que te dá clareza sobre seu momento, estrutura para suas decisões e direção para construir a profissão que você quer.',
    bundle: [
      'Material digital guiado — 69 páginas',
      'Mapa de Clareza + 4 perfis',
      'Etapa IA + Aplicação',
      'Vídeos guia com Letícia',
      'Suporte permanente',
      'Bônus - Turma Fundadora: mentoria 40min',
      'Bônus - Guia de Processos',
    ],
    price: 'R$97',
    cta: 'Sim, quero o Projete-se agora',
    sub: 'Acesso imediato · Garantia de 14 dias · Pagamento seguro',
  },
  footer: '© 2025 Projete-se · Por Letícia Schneider · Todos os direitos reservados',
};
