// Shared copy + content data for both variations of the Projete-se landing.
window.CONTENT = {
  brand: 'Projete-se',
  price: 'R$97',
  bar: {
    line: 'Projete-se — R$97 · Acesso imediato · Garantia de 14 dias',
    cta: 'Quero começar agora',
  },
  hero: {
    tag: 'Método Projete-se + IA',
    titleA: 'ARQUITETA: Cansada de se sentir perdida? Destrave sua carreira em 7 dias com o Método Projete-se + IA.',
    titleB: 'Tudo por apenas R$ 97.',
    body: 'O guia prático que organiza suas ideias, define seu próximo passo e te coloca no controle, sem mais cursos técnicos ou autoajuda vazia. Tudo por apenas R$ 97.',
    cta: 'QUERO MINHA CLAREZA AGORA!',
    sub: 'R$97 · Acesso imediato · Garantia de 14 dias',
    pills: [
      { icon: 'bolt', label: 'Acesso imediato' },
      { icon: 'shield', label: 'Garantia de 14 dias' },
      { icon: 'sparkle', label: 'Mentora IA personalizada' },
      { icon: 'mic', label: 'Bônus Mentoria em Vídeo' },
      { icon: 'clipboard', label: 'Guia de Processos' },
    ],
  },
  pains: {
    tag: 'A dor e a promessa',
    title: 'Você não precisa de mais informação, precisa de clareza e um plano de ação.',
    lead: 'Você se dedica, estuda, tenta... mas a sensação de estar sem direção persiste. O mercado está cheio de cursos técnicos que não te ajudam a entender o SEU momento. Você não precisa de mais informação, precisa de clareza e um plano de ação.',
    items: [
      { n: '01', text: 'O Projete-se é o atalho que você busca. Um material digital guiado, criado para arquitetas que querem organizar suas ideias, identificar seu perfil profissional e construir seus próximos passos com intenção.' },
      { n: '02', text: 'Não é autoajuda, não é fórmula pronta. É um processo testado, com o apoio de uma IA personalizada para te guiar.' },
    ],
    pull: 'Clareza primeiro. Ação depois.',
  },
  falseSolutions: {
    tag: 'Por que nada funcionou até agora',
    title: 'Sem mais cursos técnicos ou autoajuda vazia.',
    lead: 'O mercado está cheio de conteúdo para arquitetas. Mas aprender mais uma ferramenta não resolve quando você ainda não sabe qual direção seguir.',
    items: [
      { icon: 'play', title: 'YouTube e redes sociais', body: 'Muito conteúdo, nenhuma direção. Você aprende, consome, salva. E continua no mesmo lugar porque ninguém te perguntou primeiro onde você está.' },
      { icon: 'monitor', title: 'Cursos técnicos (SketchUp, Revit...)', body: 'Você aprendeu o software. Mas dominar a ferramenta não diz para você como, para quem e por que usá-la. A clareza não está na técnica.' },
      { icon: 'clipboard', title: 'Cursos de gestão e negócios', body: '"Aprenda a montar seu escritório em 10 passos." Ótimo — mas e quando você nem sabe que tipo de profissional quer ser? Construir sobre confusão é diferente de construir sobre clareza.' },
      { icon: 'bolt', title: 'Trabalhar mais e mais forte', body: 'Esforço sem direção só cansa mais rápido. Você não precisa de mais ação agora — precisa de mais clareza sobre para onde a ação deve ir.' },
    ],
    callout: {
      title: 'O ponto de virada',
      body: 'O Projete-se foi criado para a fase anterior à ação: a fase em que você precisa entender seu momento, organizar ideias e decidir o próximo passo com clareza.\nÉ um processo testado, com apoio de uma IA personalizada para te guiar.',
    },
  },
  product: {
    tag: 'Apresentando',
    title: 'Projete-se',
    subtitle: 'O guia prático para organizar ideias, definir o próximo passo e retomar o controle da carreira',
    nots: [
      'Não é um curso técnico',
      'Não é autoajuda',
      'Não é motivação vazia',
      'Não é fórmula pronta',
    ],
    body: 'O Projete-se é um material digital guiado, criado para arquitetas que querem identificar seu perfil profissional e construir próximos passos com intenção. Você entende onde está, organiza o que sente e sai com uma direção mais clara para agir.',
    cta: 'Quero minha clareza agora',
    sub: 'R$97 · Acesso imediato',
  },
  profiles: {
    tag: 'Para quem é o Projete-se',
    title: 'Nem toda arquiteta vive a profissão do mesmo jeito.',
    lead: 'O Projete-se foi criado para diferentes fases da carreira — porque cada momento pede uma leitura diferente. Encontre onde você está agora:',
    items: [
      { letter: 'A', name: 'Exploradora', quote: 'Estou tentando entender meu lugar.', body: 'Você está começando ou prestes a entrar no mercado — mas ainda sem clareza de como construir sua atuação com direção, segurança e identidade.' },
      { letter: 'B', name: 'Realizadora', quote: 'Eu faço muita coisa, mas tudo parece bagunçado.', body: 'Você já atende, já entrega. Mas muita coisa ainda depende do improviso, da correria e da sua energia para tudo funcionar.' },
      { letter: 'C', name: 'Expansora', quote: 'Quero crescer, mas desse jeito está pesado demais.', body: 'Você não está mais no início. Existe movimento e experiência — mas o peso da rotina torna o crescimento mais difícil do que deveria.' },
      { letter: 'D', name: 'Experiente', quote: 'Já caminhei bastante, mas sinto que preciso me reencontrar.', body: 'Você acumulou bagagem e prática. Mas algo estagnou, e você precisa de uma nova leitura sobre direção e próximos passos.' },
    ],
    quote: 'Não existe resposta certa. Existe identificação. O Projete-se começa exatamente de onde você está.',
  },
  process: {
    tag: 'O que você recebe',
    title: 'Seu Guia Pessoal para a Clareza: O Método Projete-se + IA',
    lead: 'Um caminho simples para entender seu momento, acessar o conteúdo certo e transformar percepção em ação.',
    items: [
      { n: '01', title: 'Descubra seu Perfil', body: 'Responda 8 perguntas e identifique se você é Exploradora, Realizadora, Expansora ou Experiente. Receba um roteiro personalizado para o seu momento.' },
      { n: '02', title: 'Material Estratégico', body: '69 páginas de reflexões profundas, organizadas para o seu perfil. Leia o que importa agora para você.' },
      { n: '03', title: 'Sua Mentora IA', body: 'Transforme percepções em ações. Nossa IA personalizada ajuda a organizar decisões, destravar prioridades e aplicar o que você aprendeu. Não é uma conversa genérica: ela entende seu perfil e suas necessidades.' },
      { n: '+', title: 'Bônus: Mentoria em Vídeo (40min)', body: 'Letícia te orienta em cada etapa, como se estivesse ao seu lado.' },
      { n: '↗', title: 'Bônus: Guia de Processos', body: 'Leve a clareza para a rotina com um material prático para organizar seus projetos.' },
    ],
  },
  ai: {
    tag: 'I.A + Aplicação',
    title: 'Sua Mentora IA para transformar percepções em ações.',
    lead: 'Nossa IA personalizada te ajuda a organizar decisões, destravar prioridades e aplicar o que aprendeu.',
    body: 'Ela entende seu perfil e suas necessidades, para que a conversa não seja genérica.',
    bullets: [
      'Organiza decisões.',
      'Destrava prioridades.',
      'Ajuda a aplicar o método no seu momento real.',
    ],
    status: 'Mentora Projete-se ativa',
  },
  transformation: {
    tag: 'O antes e o depois',
    title: 'O que muda depois do Projete-se',
    before: {
      label: 'Antes do Projete-se',
      items: [
        'Dúvida e confusão sobre a carreira',
        'Sensação de pouca direção e propósito',
        'Esforço sem resultados claros',
      ],
    },
    after: {
      label: 'Depois do Projete-se',
      items: [
        'Clareza total sobre sua fase profissional',
        'Direção e identidade definidas',
        'Decisões intencionais e próximos passos claros',
        'Construção de carreira com propósito e organização',
      ],
    },
  },
  mentor: {
    tag: 'Quem criou o Projete-se',
    name: 'Letícia Schneider',
    role: 'Arquiteta · Criadora do Projete-se',
    lead: 'Arquiteta. Que um dia também estava sem direção — e não encontrou nenhum material que a ajudasse a entender seu momento antes de agir.',
    body: [
      'Letícia Schneider sabe exatamente o que você está vivendo — porque ela viveu também.',
      'Quando começou como arquiteta, tinha vontade, tinha habilidade, mas não tinha clareza. Não sabia bem para onde ir, o que priorizar, que tipo de profissional queria construir. Ela procurou um material que a ajudasse a entender seu próprio momento — e não encontrou nada.',
      'Só cursos técnicos. Só gestão de escritório. Só conteúdo para quem já sabia quem era e só precisava de mais ferramentas.',
      'Ela construiu o próprio caminho. Criou seu escritório no Vale do Araguaia, desenvolveu uma metodologia que funcionou para ela — e que pode funcionar para você.',
      'O Projete-se nasceu da lacuna que ela viveu na pele. Para que nenhuma outra arquiteta precise começar sem o ponto de partida certo.',
    ],
    quote: 'Nem sempre o que você precisa é de mais informação. Às vezes, é só do ponto de partida certo.',
    quoteBy: 'Letícia Schneider',
  },
  testimonials: [
    {
      text: 'Gostei muito disso de já ter acesso a materiais que apoiam a mudança na prática. Dá uma sensação de continuidade muito boa.',
      image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150&h=150',
      name: 'Ana Paula Ribeiro',
      role: 'Leitora do Projete-se • Anápolis, GO',
    },
    {
      text: 'Nossa, de verdade... superou muito o que eu estava esperando.',
      image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150&h=150',
      name: 'Mariana Alves',
      role: 'Leitora do Projete-se • Ribeirão Preto, SP',
    },
    {
      text: 'Foi o primeiro lugar onde eu senti clareza de verdade. Não é um e-book que você só lê... é um processo.',
      image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=150&h=150',
      name: 'Ana Beatriz Souza',
      role: 'Leitora do Projete-se • Sinop, MT',
    },
    {
      text: 'Achei que seria algo mais simples, mas me deu um norte mesmo.',
      image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150&h=150',
      name: 'Camila Nogueira',
      role: 'Leitora do Projete-se • Rio Verde, GO',
    },
  ],
  bonus: {
    tag: 'E tem mais',
    title: 'Bônus exclusivos',
    label: 'BÔNUS - MENTORIA EM VÍDEO — incluso na oferta',
    name: 'Mentoria em vídeo em grupo com Letícia Schneider — 40 minutos',
    body: 'Uma mentoria em vídeo em grupo com 40 minutos ao lado de Letícia para aprofundar percepções do material e receber orientação direta sobre o seu momento profissional.',
    body2: 'Você não fica sozinha no processo. Ter acesso à mentora que criou o material é o diferencial que transforma um produto digital em uma experiência real de acompanhamento.',
    note: 'Nenhum dos outros produtos do mercado oferece isso por R$97.',
    value: 'Valor real: R$197 — incluso na sua compra',
    items: [
      {
        label: 'BÔNUS - MENTORIA EM VÍDEO — incluso na oferta',
        badge: 'Bônus - Mentoria em Vídeo',
        name: 'Mentoria em vídeo em grupo com Letícia Schneider — 40 minutos',
        body: 'Letícia te orienta em cada etapa, como se estivesse ao seu lado.',
        body2: '',
        note: 'Mentoria em vídeo com 40 minutos, inclusa na sua compra.',
        value: 'R$197',
      },
      {
        label: 'BÔNUS - GUIA DE PROCESSOS — incluso na oferta',
        badge: 'Bônus - Guia de Processos',
        name: 'Guia de Processos em Excel',
        body: 'Um material prático em Excel para organizar as fases do projeto, do atendimento inicial à entrega final.',
        bullets: [
          'Reduz o improviso e aumenta a previsibilidade.',
          'Evita retrabalhos e desgastes com o cliente.',
          'Fortalece sua imagem como profissional organizada, cuidadosa e comprometida com a excelência.',
        ],
        note: 'Para transformar clareza em processo, rotina e entrega profissional.',
        value: 'R$97',
        guide: true,
      },
    ],
  },
  pricing: {
    tag: 'Tudo o que você está levando',
    title: 'A oferta completa',
    items: [
      { name: 'Projete-se — Material Digital Guiado (69 páginas)', value: 'R$197' },
      { name: 'Mapa de Clareza + 4 perfis personalizados', value: 'R$97' },
      { name: 'Vídeos guia com Letícia em cada etapa', value: 'R$97' },
      { name: 'Etapa IA + Aplicação — prompts e direcionamentos', value: 'R$67' },
      { name: 'BÔNUS — Mentoria em vídeo em grupo com Letícia (40min)', value: 'R$197', bonus: true },
      { name: 'BÔNUS — Guia de Processos em Excel: fases de projeto do atendimento inicial à entrega final', value: 'R$97', bonus: true },
    ],
    total: 'R$752',
    today: 'R$97',
    installment: '12x de R$10,03',
    installmentPrefix: '12x de',
    installmentValue: 'R$10,03',
    cashLine: 'ou R$97 à vista',
    todayLine: 'Você paga hoje:',
    framing: 'Invista na sua clareza hoje por apenas:',
    cta: 'Quero minha clareza agora',
    sub: 'Clique, pague e receba o acesso em segundos. Kiwify · Pagamento seguro',
    compare: [
      'Cursos técnicos como SketchUp e Revit custam de R$97 a R$299 — e não te dizem para onde ir com a ferramenta.',
      'Programas de gestão de escritório custam até R$497 — e assumem que você já sabe quem é.',
      'O Projete-se custa R$97. E começa exatamente de onde você está.',
    ],
  },
  guarantee: {
    title: 'Garantia de 14 dias',
    body: 'Se em 14 dias você sentir que o Projete-se não é para você, é só me enviar um e-mail e eu devolvo 100% do valor — sem perguntas, sem burocracia.',
    note: 'Compra sem risco. Totalmente.',
    cta: 'Quero minha clareza agora',
  },
  faq: {
    tag: 'Perguntas frequentes',
    title: 'Suas dúvidas, respondidas.',
    items: [
      { q: 'Isso é para mim se eu ainda estou na faculdade?', a: 'Sim. Se você está no último ano ou prestes a entrar no mercado e já sente aquela sensação de "e agora?" — o Projete-se foi criado exatamente para esse momento. Quanto antes você tiver clareza sobre quem é como profissional, mais segura e intencional vai ser sua entrada no mercado.' },
      { q: 'Funciona para quem já atua há alguns anos?', a: 'Sim. O Projete-se tem etapas específicas para quem está em fase de reorganização profissional — os perfis Realizadora, Expansora e Experiente foram criados para arquitetas que já atuam mas sentem que algo está solto, pesado ou travado. O material começa de onde você está hoje, não de onde você começou.' },
      { q: 'Preciso usar a IA obrigatoriamente?', a: 'Não. A IA é um recurso de apoio dentro do processo — não é o produto. Você percorre as etapas de leitura e percepção normalmente, e a IA entra como uma ferramenta complementar para quem quiser aprofundar ainda mais as respostas. Funciona perfeitamente sem ela.' },
      { q: 'Quanto tempo tenho para acessar o material?', a: 'O acesso é permanente. Você pode percorrer no seu ritmo, voltar quantas vezes quiser, relembrar etapas específicas conforme sua carreira evolui. O Projete-se não é um conteúdo que você consome uma vez — é um processo ao qual você pode sempre retornar.' },
      { q: 'Quando acontece a mentoria ao vivo com Letícia?', a: 'As datas das sessões de mentoria em grupo são divulgadas dentro da plataforma. Ao comprar, você garante a sua vaga na próxima turma. Caso não consiga participar ao vivo, a gravação fica disponível para quem adquirir o acesso à gravação por R$47,90.' },
      { q: 'Qual é a forma de pagamento?', a: 'Pagamento único de R$97 via cartão de crédito, débito ou Pix, ou 12x de R$10,03. O acesso é liberado imediatamente após a confirmação do pagamento, direto pela plataforma Kiwify.' },
      { q: 'E se eu não gostar?', a: 'Garantia de 14 dias, sem perguntas. Se por qualquer motivo o Projete-se não fizer sentido para você, é só enviar um e-mail dentro do prazo e devolvo 100% do valor. Compra totalmente sem risco.' },
    ],
  },
  close: {
    title: 'Chega de se sentir perdida. Sua carreira merece clareza.',
    pathA: 'Acesso Imediato ao Método Projete-se + IA e todos os bônus.',
    pathB: 'Garantia Incondicional de 14 dias: satisfação ou seu dinheiro de volta.',
    bundle: [
      'Acesso Permanente: estude no seu ritmo, de qualquer dispositivo.',
      'Método Projete-se + IA',
      'Mentoria em Vídeo de 40min',
      'Guia de Processos',
    ],
    price: 'R$97',
    cta: 'QUERO MINHA CLAREZA AGORA!',
    sub: 'Acesso imediato · Garantia de 14 dias · Pagamento seguro',
  },
  footer: '© 2025 Projete-se · Por Letícia Schneider · Todos os direitos reservados',
};
